### ISSUE TITLE
Design workflow for managing multiple crews simultaneously

### ISSUE THREAD

**Issue by Widdershin** [save-the-shoes/save-the-shoes#18]
Currently, you can only run one set of timers at once. As an ECO, sometimes you need to manage the times of up to 4 crews at once. We should support this in the app, but first we need to put thought into how it should work.

**Comment by akampjes** [comment]
Should hopefully be able to turn most of the app into a component and reuse that 4 times :smiley_cat:

**Comment by akampjes** [comment]
Could have multiple screens to swipe between for each timer, each screen has a different colour to identify the crew quickly.

Additionally we may want to display an overview screen that displays what stage each team is up to.

**Comment by snickersmstn** [comment]
Both sound like a good idea andrew, the colour thing would be good easy want to ID which crew you are dealing with,
